export const UC_AUTH_API_CALL_REQUEST = "UC_AUTH_API_CALL_REQUEST";
export const UC_AUTH_API_CALL_SUCCESS = "UC_AUTH_API_CALL_SUCCESS";
export const UC_AUTH_API_CALL_FAILURE = "UC_AUTH_API_CALL_FAILURE";
export const UC_AUTH_API_CALL_FETCH = "UC_AUTH_API_CALL_FETCH";
