// export const API_CALL_REQUEST = "API_CALL_REQUEST_UC_AUTO";
// export const API_CALL_SUCCESS = "API_CALL_SUCCESS_UC_AUTO";
// export const API_CALL_FAILURE = "API_CALL_FAILURE_UC_AUTO";
// export const FETCH_USERSCOURSE = "FETCH_USERSCOURSE_AUTO";

export const UC_AUTO_API_CALL_REQUEST = "UC_AUTO_API_CALL_REQUEST";
export const UC_AUTO_API_CALL_SUCCESS = "UC_AUTO_API_CALL_SUCCESS";
export const UC_AUTO_API_CALL_FAILURE = "UC_AUTO_API_CALL_FAILURE";
export const UC_AUTO_API_CALL_FETCH = "UC_AUTO_API_CALL_FETCH";
export const UC_AUTO_SET_CURRENT_PAGE = "UC_AUTO_SET_CURRENT_PAGE";
export const UC_AUTO_SET_USERS_COUNT = "UC_AUTO_SET_USERS_COUNT";
export const UC_AUTO_USERS_FOLLOW = "UC_AUTO_USERS_FOLLOW";
export const UC_AUTO_USERS_UNFOLLOW = "UC_AUTO_USERS_UNFOLLOW";
export const UC_AUTO_USERS_FOLLOWED_START = "UC_AUTO_USERS_FOLLOWED_START";
export const UC_AUTO_USERS_IS_FOLLOWED_PROGRESS = "UC_AUTO_USERS_IS_FOLLOWED_PROGRESS";
export const UC_AUTO_USERS_IS_FOLLOWED_PROGRESS_TRUE = "UC_AUTO_USERS_IS_FOLLOWED_PROGRESS_TRUE";
export const UC_AUTO_USERS_IS_FOLLOWED_PROGRESS_FALSE = "UC_AUTO_USERS_IS_FOLLOWED_PROGRESS_FALSE";
