export const UC_API_CALL_LOGIN = "UC_API_CALL_LOGIN";
export const UC_API_CALL_LOGIN_REQUEST = "UC_API_CALL_LOGIN_REQUEST";
export const UC_API_CALL_LOGIN_SUCCESS = "UC_API_CALL_LOGIN_SUCCESS";
export const UC_API_CALL_LOGIN_FAILURE = "UC_API_CALL_LOGIN_FAILURE";

export const UC_API_CALL_LOGOUT = "UC_API_CALL_LOGOUT";

export const UC_AUTH_API_CALL_REQUEST = "UC_AUTH_API_CALL_REQUEST";
export const UC_AUTH_API_CALL_SUCCESS = "UC_AUTH_API_CALL_SUCCESS";
export const UC_AUTH_API_CALL_FAILURE = "UC_AUTH_API_CALL_FAILURE";
export const UC_AUTH_API_CALL_FETCH = "UC_AUTH_API_CALL_FETCH";
