export const UC_PROFILE_API_CALL_REQUEST = "UC_PROFILE_API_CALL_REQUEST";
export const UC_PROFILE_API_CALL_SUCCESS = "UC_PROFILE_API_CALL_SUCCESS";
export const UC_PROFILE_API_CALL_FAILURE = "UC_PROFILE_API_CALL_FAILURE";
export const UC_PROFILE_API_CALL_FETCH = "UC_PROFILE_API_CALL_FETCH";
