export const UC_AUTO_API_CALL_REQUEST = "UC_PROFILE_API_CALL_REQUEST";
export const UC_AUTO_API_CALL_SUCCESS = "UC_PROFILE_API_CALL_SUCCESS";
export const UC_AUTO_API_CALL_FAILURE = "UC_PROFILE_API_CALL_FAILURE";
export const UC_AUTO_API_CALL_FETCH = "UC_PROFILE_API_CALL_FETCH";
export const UC_AUTO_SET_CURRENT_PAGE = "UC_PROFILE_SET_CURRENT_PAGE";
export const UC_AUTO_SET_USERS_COUNT = "UC_PROFILE_SET_USERS_COUNT";