export const API_CALL_REQUEST = "API_CALL_REQUEST_UC_AUTO";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS_UC_AUTO";
export const API_CALL_FAILURE = "API_CALL_FAILURE_UC_AUTO";
export const FETCH_USERSCOURSE = "FETCH_USERSCOURSE_AUTO";