export const DOG_API_CALL_REQUEST = "DOG_API_CALL_REQUEST";
export const DOG_API_CALL_SUCCESS = "DOG_API_CALL_SUCCESS";
export const DOG_API_CALL_FAILURE = "DOG_API_CALL_FAILURE";
export const DOG_API_CALL_FETCH = "DOG_API_CALL_FAILURE";

export const UC_API_CALL_REQUEST = "UC_API_CALL_REQUEST";
export const UC_API_CALL_FAILURE = "UC_API_CALL_FAILURE";
export const UC_API_CALL_SUCCESS = "UC_API_CALL_SUCCESS";
export const UC_API_CALL_FETCH = "UC_API_CALL_FETCH";

export const UC_AUTO_API_CALL_REQUEST = "UC_AUTO_API_CALL_REQUEST";
export const UC_AUTO_API_CALL_SUCCESS = "UC_AUTO_API_CALL_SUCCESS";
export const UC_AUTO_API_CALL_FAILURE = "UC_AUTO_API_CALL_FAILURE";
export const UC_AUTO_API_CALL_FETCH = "UC_AUTO_API_CALL_FETCH";

export const WFC_API_CALL_REQUEST = "WFC_API_CALL_REQUEST";
export const WFC_API_CALL_SUCCESS = "WFC_API_CALL_SUCCESS";
export const WFC_API_CALL_FAILURE = "WFC_API_CALL_FAILURE";
export const WFC_API_CALL_FETCH = "WFC_API_CALL_FAILURE";