export const UC_API_CALL_LOGOUT = "UC_API_CALL_LOGOUT";
export const UC_API_CALL_LOGOUT_REQUEST = "UC_API_CALL_LOGIN_REQUEST";
export const UC_API_CALL_LOGOUT_SUCCESS = "UC_API_CALL_LOGIN_SUCCESS";
export const UC_API_CALL_LOGOUT_FAILURE = "UC_API_CALL_LOGIN_FAILURE";


