export const BGU_API_CALL_REQUEST = "BGU_API_CALL_REQUEST";
export const BGU_API_CALL_SUCCESS = "BGU_API_CALL_SUCCESS";
export const BGU_API_CALL_FAILURE = "BGU_API_CALL_FAILURE";
export const BGU_API_CALL_FETCH = "BGU_API_CALL_FETCH";
export const BGU_SET_CURRENT_PAGE = "UC_AUTO_SET_CURRENT_PAGE";
export const BGU_SET_USERS_COUNT = "UC_AUTO_SET_USERS_COUNT";